import Link from "next/link";
import { notFound } from "next/navigation";
import { FeatureGrid, MarketingPage } from "../../src/features/product/PublicShell";
import {
  CHROME_EXTENSION_PUBLICLY_INSTALLABLE,
  CHROME_EXTENSION_VERSION,
  CHROME_WEB_STORE_URL,
} from "../../src/platform/distribution";

type PageSpec = { eyebrow: string; title: string; summary: string; sections: { title: string; body: string }[] };
const PAGES: Record<string, PageSpec> = {
  product: { eyebrow: "Controlled pilot", title: "An Airboard when you need a workspace. Preview overlays when you need the room.", summary: "Create persistent diagrams in the standalone web workspace. Voice, gesture, screen presentation, Google Meet and native desktop capabilities depend on browser support and the preview channel identified on each integration page.", sections: [{ title: "Standalone workspace", body: "Organize persistent boards, version changes, share, export and present over a selected screen without moving the audience into another tab." }, { title: "Google Meet private preview", body: "The Chrome preview renders a private engine. The audience sees the outgoing composite; settings, logs and setup remain in the Airboard account." }, { title: "Native desktop development build", body: "The Electron development surface is transparent, frameless, always-on-top and click-through. Signed installers and automatic updates are not yet generally distributed." }] },
  enterprise: { eyebrow: "Enterprise design partners", title: "Visual collaboration with an accountable pilot control plane.", summary: "Evaluate Airboard with organization policy, installation health, audit events, deleted-board recovery controls, SSO configuration and SCIM provisioning. Production identity-provider activation still requires Airboard operator review.", sections: [{ title: "Deployment control", body: "Choose allowed platforms, external-guest behavior, media features, exports and the deleted-board recovery window at organization level." }, { title: "Security evidence", body: "Tenant isolation, signed session admission, scoped installation identity and content-free analytics establish the implemented baseline. Independent security testing remains a launch gate." }, { title: "Commercial evaluation", body: "Design partners receive a managed proof of concept with a sponsor, success criteria, security review and rollout decision." }] },
  templates: { eyebrow: "Starting points", title: "Begin with the visual language your conversation needs.", summary: "Airboard templates will cover architecture, decision flows, teaching, discovery workshops and customer demonstrations.", sections: [{ title: "System architecture", body: "Services, APIs, databases, queues, users and clear directional connections." }, { title: "Decision workshop", body: "Branches, alternatives, risks, owners and next actions." }, { title: "Teaching canvas", body: "High-contrast composition that remains legible over slides, documents and camera video." }] },
  demo: { eyebrow: "Product tour", title: "See the idea, the gesture and the outgoing result together.", summary: "The interactive product workspace is available after signup; the meeting preflight verifies the private engine before a real call.", sections: [{ title: "1. Say or type the intent", body: "Create, connect, rename, move and revise diagram objects using deterministic commands with bounded semantic recovery." }, { title: "2. Place it naturally", body: "Pointer and camera gestures share the same crop-aware coordinate transform." }, { title: "3. Verify the audience output", body: "Airboard checks compositor engagement, sender attachment, encoded frames and outbound bytes before calling the integration ready." }] },
  download: { eyebrow: "Install Airboard", title: "Put Airboard where you work.", summary: "Use the web workspace now or request a controlled preview of an integration that has not completed store distribution.", sections: [{ title: "Chrome for Google Meet", body: "The camera overlay is shown as a private preview until the reviewed Chrome Web Store detail URL is configured." }, { title: "Desktop overlay", body: "Signed, auto-updating installers are required before general distribution." }, { title: "Web workspace", body: "No installation required. Sign in and create a persistent Airboard from any supported desktop browser." }] },
  security: { eyebrow: "Pilot trust center", title: "Clear boundaries around identity, media and customer content.", summary: "The implemented pilot baseline uses tenant-scoped access, signed session admission and content-free product telemetry. This is not a certification claim.", sections: [{ title: "Media and voice", body: "Raw camera and microphone media is processed live and is not stored by Airboard. Deepgram receives live audio during Airo transcription; OpenAI receives bounded text and board context only for semantic fallback." }, { title: "Access", body: "API identity comes from verified authentication tokens. Organizations, memberships and database row-level security isolate customer data." }, { title: "Operations", body: "Audit events, webhook idempotency, sanitized short-lived diagnostics, readiness checks and lifecycle jobs form the operational baseline. Independent penetration testing and a completed incident exercise remain launch gates." }] },
  docs: { eyebrow: "Documentation", title: "Set up Airboard without guessing.", summary: "Documentation is organized around standalone use, supported integrations, privacy controls, administration and troubleshooting.", sections: [{ title: "Getting started", body: "Create an account, select your platform, run private preflight and begin the trial only when the setup passes." }, { title: "Google Meet", body: "Connect the Chrome extension from its popup, review media disclosure, verify the sender and confirm from a real receiver." }, { title: "Administration", body: "Invite members, set policy, inspect installations and export audit events from the organization console." }] },
  support: { eyebrow: "Pilot support", title: "Diagnose the capability, not the customer’s conversation.", summary: "User-created support bundles contain versions, permissions, capability state, timings, error codes and trace IDs. The implemented bundle path excludes customer content.", sections: [{ title: "Self-service", body: "Check integration health and rerun preflight before entering a customer meeting." }, { title: "Support bundle", body: "Create a seven-day sanitized diagnostic bundle from Privacy & data settings and copy its ID." }, { title: "Contact", body: "For pilot assistance, email hellosigmascience@gmail.com with the bundle ID—not a meeting URL, transcript or board content." }] },
  status: { eyebrow: "Status-page placeholder", title: "Airboard does not yet operate a public incident feed.", summary: "The authenticated product can check API readiness, but this marketing page is not live operational monitoring and must not be read as an uptime commitment.", sections: [{ title: "Web app", body: "A production status provider, component checks and incident publishing workflow remain to be connected." }, { title: "Realtime and API", body: "The API readiness endpoint checks the control-plane database and reports provider configuration separately." }, { title: "Meeting integrations", body: "Preview incidents are handled through the pilot support channel until public incident communication is operational." }] },
  changelog: { eyebrow: "Changelog", title: "What changed in Airboard.", summary: "Product, security and integration changes should be visible to customers in plain language.", sections: [{ title: "Commercial control plane", body: "Added accounts, organizations, trial and billing lifecycle, persistent boards, policies, analytics, audit and privacy workflows." }, { title: "Meet overlay", body: "Removed the dedicated in-meeting canvas and kept only the outgoing camera composite with private controls." }, { title: "Canvas composition", body: "Removed the separate presentation wizard, added automatic screen/camera/dark source priority, snap-to-hide, adaptive contrast and crop-aware gesture alignment. Camera composites keep a strict video, dark-overlay and diagram order." }] },
  "contact-sales": { eyebrow: "Talk to Airboard", title: "Design an evaluation around a real outcome.", summary: "Enterprise evaluations use a managed proof of concept rather than a three-day self-serve trial.", sections: [{ title: "What to bring", body: "Primary meeting platform, expected presenters, client and OS mix, compliance needs, data region and a measurable success criterion." }, { title: "What we provide", body: "A pilot owner, deployment plan, current security material, test matrix, support path and a graduation decision." }, { title: "Contact", body: "Submit the evaluation request form. Requests are stored in the Airboard control plane for manual follow-up; a CRM is not yet connected." }] },
  privacy: { eyebrow: "Pilot privacy notice · 25 July 2026", title: "What Airboard actually processes in the controlled pilot.", summary: "This implementation-aligned product notice is not yet counsel-approved and must not be represented as a final statutory privacy notice.", sections: [{ title: "Account and workspace data", body: "Airboard stores identity, organization, membership, settings, consent, owned boards and versions, sharing records, integration state, audit events and billing references needed to provide and secure the service." }, { title: "Camera, microphone and voice", body: "Airboard processes raw media live and does not store it. Deepgram receives audio while Airo transcription is active. OpenAI can receive bounded command text and board context only when deterministic parsing cannot safely finish." }, { title: "Requests, support and abuse prevention", body: "Evaluation forms store name, email, company, company size, use case and a short one-way IP hash. Authenticated support stores the subject and message a user submits. Users are told not to include board content, transcripts or meeting URLs." }, { title: "Diagnostics and analytics", body: "Product analytics excludes board labels, transcripts, meeting URLs, raw media and credentials and is deleted after 90 days. Sanitized voice traces expire within 14 days; support diagnostics at seven days; audit metadata, leads and resolved support records at 365 days." }, { title: "Retention and controls", body: "Active boards remain until deletion. Deleted boards are purged after the organization recovery window. Export files expire after seven days. Users can request JSON export or account deletion; account deletion has a seven-day cancellation window." }] },
  terms: { eyebrow: "Pilot terms draft · 25 July 2026", title: "Draft terms for the Airboard controlled product release.", summary: "These implementation-aligned terms require counsel approval and legal-entity details before paid or general availability. They are displayed for transparency, not represented as executed terms.", sections: [{ title: "Service", body: "Airboard provides a standalone visual workspace. Google Meet and desktop integrations are previews and may change; Zoom and Microsoft Teams are not currently supported product channels." }, { title: "Customer responsibilities", body: "Customers must have authority to connect accounts, enable media processing, invite participants and add content, and must give meeting notices where law or policy requires them." }, { title: "Trials and subscriptions", body: "The pilot trial lasts 72 hours from successful activation. Paid checkout is available only if the billing page explicitly shows it as enabled; otherwise displayed prices are proposals and no subscription is offered." }, { title: "Acceptable use", body: "Do not use Airboard to violate law, rights, meeting policies, security controls or service limits." }] },
  dpa: { eyebrow: "Unexecuted legal draft", title: "Airboard does not yet offer an executed DPA.", summary: "A counsel-approved DPA must define controller and processor roles, instructions, security measures, subprocessors, transfers and deletion commitments before enterprise contracting.", sections: [{ title: "Technical scope identified", body: "Account, organization and board data is stored to provide the service; live media is processed only for enabled capabilities and is not stored by Airboard." }, { title: "Draft security annex inputs", body: "Tenant-scoped access, signed admission, transport encryption, managed deployment secrets, audit events and lifecycle deletion are implemented inputs. Backup, recovery, incident response and independent-test evidence still require completion." }, { title: "Completion gate", body: "The legal entity, registered address, governing law, transfer mechanism, vendor details and signed annexes are still required." }] },
  subprocessors: { eyebrow: "Pilot transparency draft", title: "Providers present in the Airboard architecture.", summary: "This is an implementation inventory, not yet the contractual subprocessor list. Legal entity names, processing locations, transfer terms and change notification still require counsel and vendor confirmation.", sections: [{ title: "Supabase", body: "Authentication, Postgres database and related platform services where configured." }, { title: "Google Cloud", body: "Current pilot web and API hosting in asia-south1." }, { title: "Deepgram", body: "Realtime transcription only while Airo is enabled and the provider is configured." }, { title: "OpenAI", body: "Bounded semantic command interpretation only when deterministic parsing cannot safely finish a command." }, { title: "Stripe and Resend", body: "Subscription billing and lifecycle email delivery only when production credentials are configured." }] },
  cookies: { eyebrow: "Browser storage", title: "Necessary storage first; optional analytics by consent.", summary: "Airboard uses authentication storage, installation state and preferences to provide the service.", sections: [{ title: "Necessary", body: "Authentication session, security state, trial/account routing and integration preferences." }, { title: "Optional analytics", body: "Marketing analytics should remain disabled until the visitor makes a consent choice where required." }] },
  accessibility: { eyebrow: "Accessibility work in progress", title: "Every core workflow needs a non-camera, non-microphone path.", summary: "Pointer, keyboard and typed commands are the baseline while gesture and voice enhance the product. Airboard has not yet completed an independent accessibility audit or published a conformance report.", sections: [{ title: "Input", body: "Create, select, edit, move, undo, delete and export are intended to remain operable without camera or microphone; the release matrix must verify each path." }, { title: "Presentation", body: "Reduced motion, focus visibility, contrast and screen-reader structure remain explicit launch requirements." }, { title: "Feedback", body: "Report pilot accessibility barriers to hellosigmascience@gmail.com." }] },
};

export default async function MarketingSlugPage({ params }: { params: Promise<{ marketingSlug: string }> }) {
  const { marketingSlug } = await params;
  if (marketingSlug === "pricing") return <Pricing />;
  if (marketingSlug === "download") return <Download />;
  const page = PAGES[marketingSlug];
  if (!page) notFound();
  return <MarketingPage eyebrow={page.eyebrow} title={page.title} summary={page.summary}><FeatureGrid items={page.sections.map((section) => ({ title: section.title, description: section.body }))} />{["product","demo","templates"].includes(marketingSlug) ? <div className="content-cta"><h2>Try the standalone Airboard pilot.</h2><p>The 72-hour trial begins at first value. Meeting and desktop surfaces require preview access.</p><Link className="button button-primary" href="/signup">Join pilot</Link></div> : null}</MarketingPage>;
}

function Download() {
  return (
    <MarketingPage eyebrow="Install Airboard" title="Put the idea directly into the conversation." summary="Use Airboard on the web today. The Google Meet camera overlay installs through Chrome; it never asks your audience to open a second canvas.">
      <div className="download-grid">
        <article className="download-primary-card" id="chrome">
          <span className="feature-badge">{CHROME_EXTENSION_PUBLICLY_INSTALLABLE ? "Available for Chrome" : "Private preview"}</span>
          <p className="eyebrow">Google Meet · v{CHROME_EXTENSION_VERSION}</p>
          <h2>Neon diagrams on your video.</h2>
          <p>Install once, connect your Airboard account, confirm live media processing, then open Meet. The extension verifies the composited sender before marking the integration ready.</p>
          {CHROME_WEB_STORE_URL ? <a className="button button-primary" href={CHROME_WEB_STORE_URL} target="_blank" rel="noreferrer">Add Airboard to Chrome</a> : <Link className="button button-primary" href="/contact-sales">Request private preview access</Link>}
          <small>{CHROME_WEB_STORE_URL ? "Chrome displays the extension permissions before installation." : "The public install button will appear only after Chrome Web Store review. Airboard does not offer a misleading or unsupported sideload button."}</small>
        </article>
        <div className="download-side-stack">
          <article id="web"><p className="eyebrow">Controlled pilot · no installation</p><h2>Web workspace</h2><p>Create persistent boards, think privately, export, or present over a selected screen in a supported desktop browser.</p><Link className="button button-quiet" href="/signup">Join pilot</Link></article>
          <article id="desktop"><p className="eyebrow">Desktop preview</p><h2>Literal click-through overlay</h2><p>The native transparent shell works over arbitrary apps. Signed installers and automatic updates are still under controlled release.</p><Link className="button button-quiet" href="/contact-sales">Request preview</Link></article>
        </div>
      </div>
    </MarketingPage>
  );
}

function Pricing() {
  return <MarketingPage eyebrow="Controlled-pilot pricing research" title="These are proposed prices, not a live purchase offer." summary="The standalone 72-hour pilot does not require a card. Paid checkout remains disabled until production billing and legal gates pass."><div className="pricing-grid"><PublicPlan name="Personal" price="$12" description="Proposed monthly price for an individual presenter." items={["Standalone workspace", "Google Meet private preview", "Desktop development preview", "Exports and supported input modes"]} /><PublicPlan name="Team" price="$18" description="Proposed monthly per-member price for shared visual work." items={["Everything in Personal", "Organization workspace", "Members and policies", "Audit and installation health"]} featured /><PublicPlan name="Enterprise" price="Custom" description="Managed design-partner evaluation." items={["Managed proof of concept", "SSO and SCIM configuration", "Deleted-board recovery controls and audit export", "Draft legal and security review package"]} enterprise /></div><p className="pricing-note">No payment is taken from this page. Final packaging and prices require pilot evidence and an approved commercial offer.</p></MarketingPage>;
}

function PublicPlan({ name, price, description, items, featured, enterprise }: { name: string; price: string; description: string; items: string[]; featured?: boolean; enterprise?: boolean }) { return <article className={`pricing-card ${featured ? "featured" : ""}`}>{featured ? <span className="feature-badge">Pilot hypothesis</span> : null}<h2>{name}</h2><p>{description}</p><div className="price"><strong>{price}</strong>{price.startsWith("$") ? <span>proposed / month</span> : null}</div><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul><Link className={`button ${featured ? "button-primary" : "button-quiet"}`} href={enterprise ? "/contact-sales" : "/signup"}>{enterprise ? "Discuss an evaluation" : "Join the pilot"}</Link></article>; }
