import Link from "next/link";
import { notFound } from "next/navigation";
import { FeatureGrid, MarketingPage } from "../../src/features/product/PublicShell";
import {
  CHROME_EXTENSION_PUBLICLY_INSTALLABLE,
  CHROME_EXTENSION_VERSION,
  CHROME_WEB_STORE_URL,
} from "../../src/platform/distribution";

type PageSpec = { eyebrow: string; title: string; summary: string; sections: { title: string; body: string }[] };
const PAGES: Record<string, PageSpec> = {
  product: { eyebrow: "One visual system", title: "An Airboard when you need a workspace. An overlay when you need the room.", summary: "Create persistent diagrams, present over a live screen, use camera-aligned gestures and voice, or carry a clean diagram directly into a supported meeting camera.", sections: [{ title: "Standalone workspace", body: "Organize persistent boards, version changes, share, export and present over a selected screen without moving the audience into another tab." }, { title: "Meeting overlay", body: "The meeting integration renders a private engine. The audience sees the outgoing composite; settings, logs and setup remain in the Airboard account." }, { title: "Native desktop layer", body: "The Electron surface is transparent, frameless, always-on-top and truly click-through over arbitrary applications." }] },
  enterprise: { eyebrow: "Enterprise Airboard", title: "Visual collaboration with an accountable control plane.", summary: "Deploy Airboard with organization policy, installation health, immutable audit events, retention controls, SSO configuration and SCIM provisioning.", sections: [{ title: "Deployment control", body: "Choose allowed platforms, external-guest behavior, media features, exports and retention at organization level." }, { title: "Security evidence", body: "Tenant isolation, signed session admission, scoped installation identity and content-free analytics establish the baseline for design-partner evaluation." }, { title: "Commercial evaluation", body: "Enterprise customers receive a managed proof of concept with a sponsor, success criteria, security review and rollout decision." }] },
  templates: { eyebrow: "Starting points", title: "Begin with the visual language your conversation needs.", summary: "Airboard templates will cover architecture, decision flows, teaching, discovery workshops and customer demonstrations.", sections: [{ title: "System architecture", body: "Services, APIs, databases, queues, users and clear directional connections." }, { title: "Decision workshop", body: "Branches, alternatives, risks, owners and next actions." }, { title: "Teaching canvas", body: "High-contrast composition that remains legible over slides, documents and camera video." }] },
  demo: { eyebrow: "Product tour", title: "See the idea, the gesture and the outgoing result together.", summary: "The interactive product workspace is available after signup; the meeting preflight verifies the private engine before a real call.", sections: [{ title: "1. Say or type the intent", body: "Create, connect, rename, move and revise diagram objects using deterministic commands with bounded semantic recovery." }, { title: "2. Place it naturally", body: "Pointer and camera gestures share the same crop-aware coordinate transform." }, { title: "3. Verify the audience output", body: "Airboard checks compositor engagement, sender attachment, encoded frames and outbound bytes before calling the integration ready." }] },
  download: { eyebrow: "Install Airboard", title: "Put Airboard where you work.", summary: "Use the web workspace now or request a controlled preview of an integration that has not completed store distribution.", sections: [{ title: "Chrome for Google Meet", body: "The camera overlay is shown as a private preview until the reviewed Chrome Web Store detail URL is configured." }, { title: "Desktop overlay", body: "Signed, auto-updating installers are required before general distribution." }, { title: "Web workspace", body: "No installation required. Sign in and create a persistent Airboard from any supported desktop browser." }] },
  security: { eyebrow: "Trust center", title: "Clear boundaries around identity, media and customer content.", summary: "Airboard is being built so commercial access is tenant-scoped, session admission is signed and telemetry never needs to inspect what users draw.", sections: [{ title: "Media", body: "Raw camera and microphone media is processed live and is not stored by default. Content diagnostics require separate explicit consent." }, { title: "Access", body: "API identity comes from verified authentication tokens. Organizations, memberships and row-level security isolate customer data." }, { title: "Operations", body: "Audit events, webhook idempotency, short-lived diagnostics, readiness checks and lifecycle jobs form the operational baseline. Independent testing remains a launch gate." }] },
  docs: { eyebrow: "Documentation", title: "Set up Airboard without guessing.", summary: "Documentation is organized around standalone use, supported integrations, privacy controls, administration and troubleshooting.", sections: [{ title: "Getting started", body: "Create an account, select your platform, run private preflight and begin the trial only when the setup passes." }, { title: "Google Meet", body: "Connect the Chrome extension from its popup, review media disclosure, verify the sender and confirm from a real receiver." }, { title: "Administration", body: "Invite members, set policy, inspect installations and export audit events from the organization console." }] },
  support: { eyebrow: "Airboard support", title: "Diagnose the capability, not the customer’s conversation.", summary: "Support bundles contain versions, permissions, capability state, timings, error codes and trace IDs. Content stays excluded unless separately authorized.", sections: [{ title: "Self-service", body: "Check integration health and rerun preflight before entering a customer meeting." }, { title: "Support bundle", body: "Create a seven-day sanitized diagnostic bundle from Privacy & data settings." }, { title: "Contact", body: "For pilot assistance, contact support@airboard.app with the diagnostic bundle ID—not a meeting URL or transcript." }] },
  status: { eyebrow: "Service health", title: "Airboard service status.", summary: "This page is the public home for incidents, planned maintenance and provider degradation.", sections: [{ title: "Web app", body: "Operational status will be populated by the production status provider." }, { title: "Realtime and API", body: "Readiness now checks the control-plane database and reports provider configuration separately." }, { title: "Meeting integrations", body: "Client-specific incidents and known exclusions will be published without exposing tenant information." }] },
  changelog: { eyebrow: "Changelog", title: "What changed in Airboard.", summary: "Product, security and integration changes should be visible to customers in plain language.", sections: [{ title: "Commercial control plane", body: "Added accounts, organizations, trial and billing lifecycle, persistent boards, policies, analytics, audit and privacy workflows." }, { title: "Meet overlay", body: "Removed the dedicated in-meeting canvas and kept only the outgoing camera composite with private controls." }, { title: "Presentation and AR", body: "Added screen underlay, broadcast-safe output, adaptive contrast, crop-aware alignment and on-device person occlusion." }] },
  "contact-sales": { eyebrow: "Talk to Airboard", title: "Design an evaluation around a real outcome.", summary: "Enterprise evaluations use a managed proof of concept rather than a three-day self-serve trial.", sections: [{ title: "What to bring", body: "Primary meeting platform, expected presenters, client and OS mix, compliance needs, data region and a measurable success criterion." }, { title: "What we provide", body: "Named technical owner, deployment plan, security material, test matrix, support path and a clear graduation decision." }, { title: "Contact", body: "Email sales@airboard.app. A CRM-backed request form should replace email before public launch." }] },
  privacy: { eyebrow: "Privacy notice · 18 July 2026", title: "Airboard processes only what is needed to provide and improve the service.", summary: "This product notice describes the implemented architecture. It must receive legal review and jurisdiction-specific contact details before general availability.", sections: [{ title: "Account and workspace data", body: "We process identity, organization, membership, settings, boards and billing references to provide Airboard and enforce access." }, { title: "Camera, microphone and voice", body: "Raw media is processed live and not stored by default. Voice providers receive live audio only while Airo is active. Diagnostics exclude transcript and board content unless separately authorized." }, { title: "Product analytics", body: "We measure activation, reliability and feature outcomes without board labels, transcripts, meeting URLs, raw media, credentials or passwords." }, { title: "Your controls", body: "Users can request export or deletion from Privacy & data. Organization policy controls integrations, media features, external guests, exports and retention." }] },
  terms: { eyebrow: "Terms · 18 July 2026", title: "Terms for the Airboard controlled product release.", summary: "These implementation-aligned terms are a product draft and require counsel approval before paid general availability.", sections: [{ title: "Service", body: "Airboard provides visual workspaces and supported meeting integrations. Preview integrations may change and are identified as previews." }, { title: "Customer responsibilities", body: "Customers must have authority to connect accounts, enable media processing, invite participants and upload content." }, { title: "Trials and subscriptions", body: "The self-serve trial lasts 72 hours from successful activation. Paid subscriptions, renewal and cancellation are managed through the billing provider." }, { title: "Acceptable use", body: "Do not use Airboard to violate law, rights, meeting policies, security controls or service limits." }] },
  dpa: { eyebrow: "Data processing", title: "Airboard data processing addendum.", summary: "The executed DPA will define controller/processor roles, instructions, security measures, subprocessors, transfers and deletion commitments.", sections: [{ title: "Scope", body: "Account, organization and board data processed to provide the service; live media processed only for enabled capabilities." }, { title: "Security measures", body: "Tenant-scoped access, signed admission, encryption in transit, managed secrets, auditability, backup and incident procedures." }, { title: "Completion gate", body: "Legal entity, governing law, transfer mechanism and signed annexes must be supplied before enterprise contracting." }] },
  subprocessors: { eyebrow: "Transparency", title: "Airboard subprocessors.", summary: "The production list must name the configured providers, purpose, processing location and change-notification process.", sections: [{ title: "Supabase", body: "Authentication, Postgres database and related platform services where configured." }, { title: "Google Cloud", body: "Current pilot web and API hosting in asia-south1." }, { title: "Deepgram", body: "Realtime transcription only when Airo is enabled and configured." }, { title: "OpenAI", body: "Bounded semantic command interpretation only when deterministic parsing cannot safely finish a command." }, { title: "Stripe and Resend", body: "Subscription billing and lifecycle email delivery when production credentials are configured." }] },
  cookies: { eyebrow: "Browser storage", title: "Necessary storage first; optional analytics by consent.", summary: "Airboard uses authentication storage, installation state and preferences to provide the service.", sections: [{ title: "Necessary", body: "Authentication session, security state, trial/account routing and integration preferences." }, { title: "Optional analytics", body: "Marketing analytics should remain disabled until the visitor makes a consent choice where required." }] },
  accessibility: { eyebrow: "Accessibility", title: "Every core workflow needs a non-camera, non-microphone path.", summary: "Pointer, keyboard and typed commands remain the baseline while gesture and voice enhance—not gate—the product.", sections: [{ title: "Input", body: "Create, select, edit, move, undo, delete and export must remain operable without camera or microphone." }, { title: "Presentation", body: "Reduced-motion, focus visibility, high contrast and screen-reader structure are release requirements." }, { title: "Feedback", body: "Report accessibility barriers to accessibility@airboard.app." }] },
};

export default async function MarketingSlugPage({ params }: { params: Promise<{ marketingSlug: string }> }) {
  const { marketingSlug } = await params;
  if (marketingSlug === "pricing") return <Pricing />;
  if (marketingSlug === "download") return <Download />;
  const page = PAGES[marketingSlug];
  if (!page) notFound();
  return <MarketingPage eyebrow={page.eyebrow} title={page.title} summary={page.summary}><FeatureGrid items={page.sections.map((section) => ({ title: section.title, description: section.body }))} />{["product","demo","templates"].includes(marketingSlug) ? <div className="content-cta"><h2>Try Airboard when the setup is ready.</h2><p>The three-day trial begins at first value, not at signup.</p><Link className="button button-primary" href="/signup">Start free</Link></div> : null}</MarketingPage>;
}

function Download() {
  return (
    <MarketingPage eyebrow="Install Airboard" title="Put the idea directly into the conversation." summary="Use Airboard on the web today. The Google Meet camera overlay installs through Chrome; it never asks your audience to open a second canvas.">
      <div className="download-grid">
        <article className="download-primary-card" id="chrome">
          <span className="feature-badge">{CHROME_EXTENSION_PUBLICLY_INSTALLABLE ? "Available for Chrome" : "Private preview"}</span>
          <p className="eyebrow">Google Meet · v{CHROME_EXTENSION_VERSION}</p>
          <h2>Neon diagrams on your video.</h2>
          <p>Install once, connect your Airboard account, confirm live media processing, then open Meet. The extension verifies the composited sender before marking the integration ready.</p>
          {CHROME_WEB_STORE_URL ? <a className="button button-primary" href={CHROME_WEB_STORE_URL} target="_blank" rel="noreferrer">Add Airboard to Chrome</a> : <Link className="button button-primary" href="/contact-sales">Request private preview access</Link>}
          <small>{CHROME_WEB_STORE_URL ? "Chrome displays the extension permissions before installation." : "The public install button will appear only after Chrome Web Store review. Airboard does not offer a misleading or unsupported sideload button."}</small>
        </article>
        <div className="download-side-stack">
          <article id="web"><p className="eyebrow">No installation</p><h2>Web workspace</h2><p>Create persistent boards, think privately, export, or present over a selected screen.</p><Link className="button button-quiet" href="/signup">Start free</Link></article>
          <article id="desktop"><p className="eyebrow">Desktop preview</p><h2>Literal click-through overlay</h2><p>The native transparent shell works over arbitrary apps. Signed installers and automatic updates are still under controlled release.</p><Link className="button button-quiet" href="/contact-sales">Request preview</Link></article>
        </div>
      </div>
    </MarketingPage>
  );
}

function Pricing() {
  return <MarketingPage eyebrow="Simple starting plans" title="Pay for presenters, not passive viewers." summary="Start without a card. Your 72-hour trial begins after your first successful setup."><div className="pricing-grid"><PublicPlan name="Personal" price="$12" description="For individual presenters and visual thinkers." items={["Standalone workspace", "Google Meet camera overlay", "Desktop click-through overlay", "Standard exports and input modes"]} /><PublicPlan name="Team" price="$18" description="Per member, for shared visual work." items={["Everything in Personal", "Organization workspace", "Members and policies", "Audit and installation health"]} featured /><PublicPlan name="Enterprise" price="Custom" description="For controlled deployment and procurement." items={["Managed evaluation", "SSO and SCIM rollout", "Custom retention and audit export", "DPA, security review and SLA"]} enterprise /></div><p className="pricing-note">Final prices remain a launch hypothesis until willingness-to-pay and pilot conversion data are reviewed.</p></MarketingPage>;
}

function PublicPlan({ name, price, description, items, featured, enterprise }: { name: string; price: string; description: string; items: string[]; featured?: boolean; enterprise?: boolean }) { return <article className={`pricing-card ${featured ? "featured" : ""}`}>{featured ? <span className="feature-badge">Most collaborative</span> : null}<h2>{name}</h2><p>{description}</p><div className="price"><strong>{price}</strong>{price.startsWith("$") ? <span>/month</span> : null}</div><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul><Link className={`button ${featured ? "button-primary" : "button-quiet"}`} href={enterprise ? "/contact-sales" : "/signup"}>{enterprise ? "Contact sales" : "Start free"}</Link></article>; }
