steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=infra/cloud-run/web.Dockerfile
      - --tag=${_IMAGE}
      - --build-arg=NEXT_PUBLIC_AIRBOARD_API_URL=${_AIRBOARD_API_URL}
      - --build-arg=NEXT_PUBLIC_GOOGLE_MEET_CLOUD_PROJECT_NUMBER=${_GOOGLE_MEET_CLOUD_PROJECT_NUMBER}
      - --build-arg=NEXT_PUBLIC_SUPABASE_URL=${_SUPABASE_URL}
      - --build-arg=NEXT_PUBLIC_SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY}
      - --build-arg=NEXT_PUBLIC_CHROME_WEB_STORE_URL=${_CHROME_WEB_STORE_URL}
      - --build-arg=NEXT_PUBLIC_CHROME_EXTENSION_VERSION=${_CHROME_EXTENSION_VERSION}
      - .
images:
  - ${_IMAGE}
substitutions:
  _CHROME_WEB_STORE_URL: ""
  _CHROME_EXTENSION_VERSION: "0.8.0"
options:
  logging: CLOUD_LOGGING_ONLY
