"use client";

import { useEffect, useState } from "react";
import { airboardApi } from "../../platform/api";
import { AIRBOARD_API_URL } from "../../platform/config";
import { useAirboardAuth } from "../../platform/auth";

export function AdminPage({ section }: { section: string }) {
  if (section === "members") return <MembersAdmin />;
  if (section === "policies") return <PoliciesAdmin />;
  if (section === "audit-logs") return <AuditAdmin />;
  if (section === "installations") return <InstallationsAdmin />;
  if (section === "identity-directory") return <IdentityDirectoryAdmin />;
  return <AdminOverview />;
}

function AdminOverview() {
  const auth = useAirboardAuth();
  const [usage, setUsage] = useState({ members: 0, boards: 0, sessions30d: 0, installations: 0 });
  useEffect(() => { if (auth.accessToken) void airboardApi<{ usage: typeof usage }>("/organization/usage", { accessToken: auth.accessToken }).then((result) => setUsage(result.usage)); }, [auth.accessToken]);
  return <div><section className="app-page-heading"><p className="eyebrow">Organization administration</p><h1>{auth.account?.organization.name}</h1><p>Control access, integrations, retention and directory provisioning.</p></section><div className="metric-grid"><Metric label="Members" value={String(usage.members)} detail="Active access" /><Metric label="Boards" value={String(usage.boards)} detail="Saved workspace content" /><Metric label="Sessions" value={String(usage.sessions30d)} detail="Last 30 days" /><Metric label="Installations" value={String(usage.installations)} detail="Not revoked" /></div><div className="admin-readiness"><h2>Enterprise controls</h2>{[["Identity and tenant isolation","Implemented"],["Organization policy","Implemented"],["Audit records","Implemented"],["SAML/OIDC configuration","Operator activation required"],["SCIM 2.0 provisioning","Implemented"],["Independent penetration test","External validation required"]].map(([label,status]) => <div key={label}><span className={`status-dot ${status === "Implemented" ? "ready" : "preview"}`} /><strong>{label}</strong><em>{status}</em></div>)}</div></div>;
}

type Member = { id: string; role: string; status: string; profiles?: { display_name?: string; email?: string } };
type Invitation = { id: string; email: string; role: string; expires_at: string; accepted_at: string | null; revoked_at: string | null };
function MembersAdmin() {
  const auth = useAirboardAuth();
  const [members, setMembers] = useState<Member[]>([]);
  const [invitations, setInvitations] = useState<Invitation[]>([]);
  const [email, setEmail] = useState(""); const [role, setRole] = useState("member"); const [message, setMessage] = useState<string | null>(null);
  const reload = async () => { if (!auth.accessToken) return; const [memberResult, invitationResult] = await Promise.all([airboardApi<{ members: Member[] }>("/organization/members", { accessToken: auth.accessToken }), airboardApi<{ invitations: Invitation[] }>("/organization/invitations", { accessToken: auth.accessToken })]); setMembers(memberResult.members); setInvitations(invitationResult.invitations); };
  useEffect(() => { void reload(); }, [auth.accessToken]);
  const invite = async () => { if (!auth.accessToken) return; const result = await airboardApi<{ invitationId: string }>("/organization/invitations", { method: "POST", accessToken: auth.accessToken, body: JSON.stringify({ email, role }) }); setMessage(`Invitation queued (${result.invitationId}).`); setEmail(""); await reload(); };
  const update = async (id: string, change: Record<string, string>) => { if (!auth.accessToken) return; await airboardApi(`/organization/members/${id}`, { method: "PATCH", accessToken: auth.accessToken, body: JSON.stringify(change) }); await reload(); };
  const revoke = async (id: string) => { if (!auth.accessToken) return; await airboardApi(`/organization/invitations/${id}`, { method: "DELETE", accessToken: auth.accessToken }); await reload(); };
  return <div><section className="app-page-heading"><p className="eyebrow">People and access</p><h1>Members</h1><p>Invite, assign roles and suspend access without sharing provider credentials.</p></section><div className="invite-row"><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="teammate@company.com" /><select value={role} onChange={(event) => setRole(event.target.value)}><option value="member">Member</option><option value="viewer">Viewer</option><option value="billing">Billing</option><option value="admin">Admin</option></select><button className="button button-primary" disabled={!email} onClick={() => void invite()}>Invite</button></div>{message ? <p className="form-message">{message}</p> : null}<div className="data-table"><div className="table-head"><span>Member</span><span>Role</span><span>Status</span></div>{members.map((member) => <div key={member.id}><span><strong>{member.profiles?.display_name ?? "Member"}</strong><small>{member.profiles?.email}</small></span><span><select value={member.role} onChange={(event) => void update(member.id, { role: event.target.value })}><option value="owner">Owner</option><option value="admin">Admin</option><option value="billing">Billing</option><option value="member">Member</option><option value="viewer">Viewer</option></select></span><span><button onClick={() => void update(member.id, { status: member.status === "active" ? "suspended" : "active" })}>{member.status}</button></span></div>)}</div>{invitations.some((item) => !item.accepted_at && !item.revoked_at) ? <><h2>Pending invitations</h2><div className="data-table"><div className="table-head"><span>Email</span><span>Role</span><span>Action</span></div>{invitations.filter((item) => !item.accepted_at && !item.revoked_at).map((item) => <div key={item.id}><span><strong>{item.email}</strong><small>Expires {new Date(item.expires_at).toLocaleDateString()}</small></span><span>{item.role}</span><span><button onClick={() => void revoke(item.id)}>Revoke</button></span></div>)}</div></> : null}</div>;
}

function PoliciesAdmin() {
  const auth = useAirboardAuth();
  const [policy, setPolicy] = useState({ externalGuestsAllowed: true, voiceEnabled: true, cameraEnabled: true, gestureEnabled: true, exportsEnabled: true, contentRetentionDays: 30 });
  const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { if (!auth.accessToken) return; void airboardApi<{ policy: Record<string, unknown> }>("/organization/policies", { accessToken: auth.accessToken }).then(({ policy: value }) => { if (!value) return; setPolicy({ externalGuestsAllowed: value.external_guests_allowed !== false, voiceEnabled: value.voice_enabled !== false, cameraEnabled: value.camera_enabled !== false, gestureEnabled: value.gesture_enabled !== false, exportsEnabled: value.exports_enabled !== false, contentRetentionDays: Number(value.content_retention_days ?? 30) }); }); }, [auth.accessToken]);
  const save = async () => { if (!auth.accessToken) return; await airboardApi("/organization/policies", { method: "PATCH", accessToken: auth.accessToken, body: JSON.stringify(policy) }); setMessage("Organization policy updated and recorded in the audit log."); };
  const toggles: Array<[string, keyof Omit<typeof policy, "contentRetentionDays">]> = [["External guests","externalGuestsAllowed"],["Voice commands","voiceEnabled"],["Camera gestures and occlusion","cameraEnabled"],["Gesture control","gestureEnabled"],["Exports","exportsEnabled"]];
  return <div><section className="app-page-heading"><p className="eyebrow">Guardrails</p><h1>Organization policy</h1><p>Central controls are returned to every connected installation.</p></section><div className="policy-panel">{toggles.map(([label,key]) => <label className="setting-toggle" key={key}><div><strong>{label}</strong><span>Allowed for organization members and supported installations.</span></div><input type="checkbox" checked={policy[key]} onChange={(event) => setPolicy({ ...policy, [key]: event.target.checked })} /></label>)}<label>Content retention in days<input type="number" min="1" max="3650" value={policy.contentRetentionDays} onChange={(event) => setPolicy({ ...policy, contentRetentionDays: Number(event.target.value) })} /></label><button className="button button-primary" onClick={() => void save()}>Save policy</button>{message ? <p className="form-message">{message}</p> : null}</div></div>;
}

function IdentityDirectoryAdmin() {
  const auth = useAirboardAuth();
  const [metadataUrl, setMetadataUrl] = useState(""); const [domains, setDomains] = useState(""); const [tokenName, setTokenName] = useState("Microsoft Entra provisioning"); const [tokens, setTokens] = useState<Array<Record<string, unknown>>>([]); const [revealed, setRevealed] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  const reload = async () => { if (!auth.accessToken) return; const [identity, tokenResult] = await Promise.all([airboardApi<{ identityProvider: Record<string, unknown> | null }>("/organization/identity-provider", { accessToken: auth.accessToken }), airboardApi<{ tokens: Array<Record<string, unknown>> }>("/organization/scim-tokens", { accessToken: auth.accessToken })]); if (identity.identityProvider) { setMetadataUrl(String(identity.identityProvider.metadata_url ?? "")); setDomains(Array.isArray(identity.identityProvider.domains) ? identity.identityProvider.domains.join(", ") : ""); } setTokens(tokenResult.tokens); };
  useEffect(() => { void reload(); }, [auth.accessToken]);
  const saveIdentity = async () => { if (!auth.accessToken) return; await airboardApi("/organization/identity-provider", { method: "PATCH", accessToken: auth.accessToken, body: JSON.stringify({ protocol: "saml", metadataUrl, domains: domains.split(",").map((item) => item.trim()), enforced: false }) }); setMessage("Identity configuration saved. Operator activation is required before enforcement to prevent lockout."); await reload(); };
  const createToken = async () => { if (!auth.accessToken) return; const result = await airboardApi<{ token: string }>("/organization/scim-tokens", { method: "POST", accessToken: auth.accessToken, body: JSON.stringify({ name: tokenName }) }); setRevealed(result.token); await reload(); };
  const revoke = async (id: string) => { if (!auth.accessToken) return; await airboardApi(`/organization/scim-tokens/${id}`, { method: "DELETE", accessToken: auth.accessToken }); await reload(); };
  return <div><section className="app-page-heading"><p className="eyebrow">Enterprise identity</p><h1>SSO and directory provisioning</h1><p>Store a verified IdP configuration and provision directory users through an organization-scoped SCIM 2.0 endpoint.</p></section><div className="policy-panel"><h2>SAML identity provider</h2><label>Metadata URL<input type="url" value={metadataUrl} onChange={(event) => setMetadataUrl(event.target.value)} placeholder="https://idp.example.com/metadata" /></label><label>Verified email domains<input value={domains} onChange={(event) => setDomains(event.target.value)} placeholder="example.com, subsidiary.com" /></label><button className="button button-primary" onClick={() => void saveIdentity()}>Save SSO configuration</button>{message ? <p className="form-message">{message}</p> : null}<h2>SCIM tokens</h2><p>Base URL: <code>{AIRBOARD_API_URL}/scim/v2</code></p><div className="invite-row"><input value={tokenName} onChange={(event) => setTokenName(event.target.value)} /><button onClick={() => void createToken()}>Create token</button></div>{revealed ? <div className="privacy-card"><strong>Copy this token now. It will not be shown again.</strong><code>{revealed}</code></div> : null}<div className="data-table"><div className="table-head"><span>Token</span><span>Last used</span><span>Action</span></div>{tokens.map((token) => <div key={String(token.id)}><span><strong>{String(token.name)}</strong><small>{String(token.token_prefix)}…</small></span><span>{token.last_used_at ? new Date(String(token.last_used_at)).toLocaleString() : "Never"}</span><span>{token.status === "active" ? <button onClick={() => void revoke(String(token.id))}>Revoke</button> : "Revoked"}</span></div>)}</div></div></div>;
}

function AuditAdmin() { const auth = useAirboardAuth(); const [events, setEvents] = useState<Record<string, unknown>[]>([]); useEffect(() => { if (auth.accessToken) void airboardApi<{ events: Record<string, unknown>[] }>("/organization/audit", { accessToken: auth.accessToken }).then((result) => setEvents(result.events)); }, [auth.accessToken]); return <div><section className="app-page-heading"><p className="eyebrow">Immutable activity</p><h1>Audit log</h1><p>Administrative, security, consent, installation, billing and data-control actions.</p></section><div className="data-table audit"><div className="table-head"><span>Action</span><span>Target</span><span>Time</span></div>{events.length ? events.map((event) => <div key={String(event.id)}><span><strong>{String(event.action)}</strong><small>Request {String(event.request_id ?? "—")}</small></span><span>{String(event.target_type ?? "—")}</span><span>{new Date(String(event.occurred_at)).toLocaleString()}</span></div>) : <div><span>No audit events yet.</span></div>}</div></div>; }

function InstallationsAdmin() { const auth = useAirboardAuth(); const [items, setItems] = useState<Array<Record<string, unknown>>>([]); const reload = async () => { if (!auth.accessToken) return; const result = await airboardApi<{ installations: Array<Record<string, unknown>> }>("/integrations", { accessToken: auth.accessToken }); setItems(result.installations); }; useEffect(() => { void reload(); }, [auth.accessToken]); const revoke = async (id: string) => { if (!auth.accessToken) return; await airboardApi(`/integrations/${id}`, { method: "PATCH", accessToken: auth.accessToken, body: JSON.stringify({ revoked: true }) }); await reload(); }; return <div><section className="app-page-heading"><p className="eyebrow">Deployment health</p><h1>Installations</h1><p>Connection, version, policy, consent and last-success state for every deployment.</p></section><div className="data-table"><div className="table-head"><span>Installation</span><span>Health</span><span>Action</span></div>{items.length ? items.map((item) => <div key={String(item.id)}><span><strong>{String(item.platform)}</strong><small>Version {String(item.version ?? "unknown")}</small></span><span>{String(item.status)} · {item.last_success_at ? `verified ${new Date(String(item.last_success_at)).toLocaleString()}` : "not verified"}</span><span>{item.status !== "revoked" ? <button onClick={() => void revoke(String(item.id))}>Revoke</button> : "Revoked"}</span></div>) : <div><span>No installations connected.</span></div>}</div></div>; }

function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <article><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>; }
