import type { ChromeInstallationIdentity } from "./chromeInstallationIdentity";

export type StoredChromeInstallationIdentity = {
  platform: string;
  externalInstallationId: string | null;
  externalPackageId: string | null;
};

export type ChromeInstallationReconciliation =
  | {
      ok: true;
      action: "unchanged" | "migrate";
      externalInstallationId: string;
      externalPackageId: string;
    }
  | {
      ok: false;
      error:
        | "INSTALLATION_PLATFORM_MISMATCH"
        | "INSTALLATION_PACKAGE_MISMATCH"
        | "INSTALLATION_INSTANCE_MISMATCH";
    };

const CHROME_EXTENSION_ID = /^[a-p]{32}$/;

export function isLegacyChromeInstallationIdentity(
  stored: StoredChromeInstallationIdentity,
): boolean {
  if (stored.platform !== "chrome_meet") return false;
  const packageId = stored.externalPackageId ?? stored.externalInstallationId;
  return Boolean(
    packageId &&
    CHROME_EXTENSION_ID.test(packageId) &&
    stored.externalInstallationId === packageId
  );
}

/**
 * Plans the one-time upgrade from the historical Chrome package ID key to the
 * random UUID generated by each browser profile. The authenticated legacy row
 * may be claimed once; after that, a different profile UUID must reconnect and
 * receive its own installation credential.
 */
export function reconcileChromeInstallationIdentity(
  stored: StoredChromeInstallationIdentity,
  presented: ChromeInstallationIdentity,
): ChromeInstallationReconciliation {
  if (stored.platform !== "chrome_meet") {
    return { ok: false, error: "INSTALLATION_PLATFORM_MISMATCH" };
  }

  const packageId = stored.externalPackageId ?? stored.externalInstallationId;
  if (packageId !== presented.packageId) {
    return { ok: false, error: "INSTALLATION_PACKAGE_MISMATCH" };
  }

  if (stored.externalInstallationId === presented.instanceId) {
    return {
      ok: true,
      action: "unchanged",
      externalInstallationId: presented.instanceId,
      externalPackageId: presented.packageId,
    };
  }

  if (stored.externalInstallationId === presented.packageId) {
    return {
      ok: true,
      action: "migrate",
      externalInstallationId: presented.instanceId,
      externalPackageId: presented.packageId,
    };
  }

  return { ok: false, error: "INSTALLATION_INSTANCE_MISMATCH" };
}
